-- 문제 1) EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 합, 급여의 평균을 변수에 대입하여 출력하여 보자.
    
DECLARE
    VCOUNT NUMBER(10);
    VSUM NUMBER(10);
    VAVG NUMBER(10,2);
BEGIN    
    SELECT COUNT(*), SUM(SALARY), AVG(SALARY)
    INTO VCOUNT,VSUM,VAVG
    FROM EMPLOYEES;
    
    DBMS_OUTPUT.PUT_LINE('총 사원수 : ' || VCOUNT);
    DBMS_OUTPUT.PUT_LINE('급여의 합 : ' || VSUM);
    DBMS_OUTPUT.PUT_LINE('급여의 평균 : ' || VAVG);
END;
/

-- 문제 2) Clara 사원의 직무, 급여, 입사일자, 커미션, 부서명을 변수에 대입하여 출력하여 보자.
DECLARE
    VJOB_ID VARCHAR2(15);
    VSALARY NUMBER(10);
    VHIRE_DATE DATE;
    VCOMMISSION_PCT NUMBER(10,2);
    VDEPARTMENT_NAME VARCHAR2(10);
BEGIN    
    SELECT JOB_ID, SALARY, HIRE_DATE, COMMISSION_PCT, D.DEPARTMENT_NAME
    INTO VJOB_ID, VSALARY, VHIRE_DATE, VCOMMISSION_PCT, VDEPARTMENT_NAME
    FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE FIRST_NAME = 'Clara';  
    
    DBMS_OUTPUT.PUT_LINE('직무 : ' || VJOB_ID);
    DBMS_OUTPUT.PUT_LINE('급여 : ' || VSALARY);
    DBMS_OUTPUT.PUT_LINE('입사일자 : ' || VHIRE_DATE);
    DBMS_OUTPUT.PUT_LINE('커미션 : ' || VCOMMISSION_PCT);
    DBMS_OUTPUT.PUT_LINE('부서명 : ' || VDEPARTMENT_NAME);
END;
/
