-- transaction
DROP TABLE DEP02;

-- 테이블복사 (구조만 복사)
CREATE TABLE DEP02 
AS
SELECT * FROM DEPARTMENTS WHERE 1 = 0;

DESC DEP02;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEP02';

-- 내용복사
INSERT INTO DEP02 SELECT * FROM DEPARTMENTS;

SELECT * FROM DEP02;

SAVEPOINT C1;

DELETE FROM DEP02 WHERE DEPARTMENT_ID = 90;

ROLLBACK TO C1;

-- VIEW 생성하기 (테이블 생성 복사하기와 똑같음) 
CREATE VIEW VIEW_EMP01
AS 
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMP_COPY WHERE DEPARTMENT_ID = 10;

SELECT * FROM VIEW_EMP01;

-- EMPLOYEES 복사해서 EMP_COPY를 만들자
CREATE TABLE EMP_COPY
AS
SELECT * FROM EMPLOYEES;

SELECT * FROM EMP_COPY;

-- VIEW 제거하기
DROP VIEW VIEW_EMP01;

-- VIEW 수정하기
SELECT * FROM EMP_COPY WHERE EMPLOYEE_ID = 200;

UPDATE VIEW_EMP01 SET SALARY = 4500 WHERE EMPLOYEE_ID = 200;

-- DATA DICTIONARY(USER_TABS, USER_CONSTRAINTS, USER_CONS_COLUMNS, USER_VIEWS, USER_INDEXS)