
-- 프로시저를 통해서 사원번호를 입력하면, 사원이름, 사원월급, 사원직책 매개변수를 통해서 전달
CREATE OR REPLACE PROCEDURE EMP_PROCEDURE_OUTMODE (
    VEMPNO IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    VNAME OUT EMPLOYEES.FIRST_NAME%TYPE,
    VSALARY OUT EMPLOYEES.SALARY%TYPE,
    VJOBID OUT EMPLOYEES.JOB_ID%TYPE
)

IS
    -- 지역변수

BEGIN
SELECT FIRST_NAME, SALARY, JOB_ID INTO VNAME, VSALARY, VJOBID FROM EMPLOYEES WHERE EMPLOYEE_ID = VEMPNO;

END;
/

DECLARE
    VNAME VARCHAR2(100);
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
BEGIN
    EMP_PROCEDURE_OUTMODE (100,VNAME,VEMP_ROWTYPE.SALARY,VEMP_ROWTYPE.JOB_ID);
    DBMS_OUTPUT.PUT_LINE('이름 : ' || VEMP_ROWTYPE.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('봉급 : ' || VEMP_ROWTYPE.SALARY);
    DBMS_OUTPUT.PUT_LINE('직책 : ' || VEMP_ROWTYPE.JOB_ID);
END;
/

-- 프로시저를 워크시트에서 불러서 사용하겠다.
VARIABLE VNAME1 VARCHAR2(100);
VARIABLE VSALARY1 VANUMBER;
VARIABLE VJOBID1 VARCHAR2(10);
EXECUTE EMP_PROCEDURE_OUTMOD(100, :VNAME, :VASALARY, :VJOBID);
PRINT VANAME
PRINT SALARY
PRINT JOB_ID;

-- PROCEDURE IN OUT MODE 동시사용
CREATE OR REPLACE PROCEDURE PROCEDURE_INOUTMODE(VSALARY IN OUT VARCHAR2)
IS
BEGIN
    VSALARY := TO_CHAR(VSALARY, '$999999999');
    VSALARY := '$'||SUBSTR(VSALARY,-9,3) || ',' || SUBSTR(VSALARY,-6,3) || ',' || SUBSTR(VSALARY,-3,3);
END;
/

DECLARE 
    VSALARY VARCHAR2(20) := '123456789';
    
BEGIN
    PROCEDURE_INOUTMODE(VSALARY);
    DBMS_OUTPUT.PUT_LINE('VSALARY = '||VSALARY); 
    
END;
/