-- 순위함수 RANK(), DENSE_RANK, ROWNUM
-- ROWNUM 구하는 순위 (공동순위는 없다.) 게시판, 공지사항, 자료실, 장바구니....에 쓰인다
DROP TABLE EMP02;
CREATE TABLE EMP02 AS SELECT * FROM EMPLOYEES WHERE 1 = 1 ;
SELECT * FROM EMP02;
SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES;
SELECT ROWNUM, FIRST_NAME, SALARY FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC);

-- 공동순위를 구하는 방법 RANK(), DENSE_RANK()
SELECT ROWNUM, RANK() OVER(ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM, RANK() OVER(ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY 
FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC);

SELECT ROWNUM, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK, FIRST_NAME, SALARY 
FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC);

-- Steven 연봉 순위는
SELECT RANK() OVER(ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY FROM EMP02 WHERE FIRST_NAME = 'Steven' 
ORDER BY SALARY DESC;

-- 중복 순위를 없애기 
SELECT RANK() OVER(ORDER BY SALARY DESC, COMMISSION_PCT DESC, DEPARTMENT_ID DESC) AS RANK, FIRST_NAME, SALARY ,
COMMISSION_PCT, DEPARTMENT_ID FROM EMPLOYEES ORDER BY SALARY DESC;

-- 부서별 순위 구하기
SELECT DEPARTMENT_ID, RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC, COMMISSION_PCT DESC, 
DEPARTMENT_ID DESC) AS RANK, FIRST_NAME, SALARY, COMMISSION_PCT 
FROM EMPLOYEES ORDER BY DEPARTMENT_ID, SALARY, COMMISSION_PCT DESC;

-- ROWNUM 규칙 중요(조심)
-- 2PAGE
-- START := ((NUM_PAGE_NO-1_ * NUM_PAGE_SIZE) + 1 #출력 페이지 시작행 (EX.11)
-- END := (NUM_PAGE_NO * NUM_PAGE_SIZE)           #출력 페이지 마지막행(EX.20)

SELECT * FROM EMPLOYEES WHERE ROWNUM BETWEEN 11 AND 20;
SELECT ROWNUM, E.* FROM EMPLOYEES E;
-- 순위 구하는 방법 (비추)
SELECT RNUM, FIRST_NAME, SALARY, DEPARTMENT_ID FROM (SELECT ROWNUM AS RNUM, E.* FROM EMPLOYEES E)
WHERE RNUM BETWEEN 100 AND 110;

-- 순위 구하는 방법 (강추) -- 속도는 이것이 빠르다
SELECT RNUM, FIRST_NAME, SALARY, DEPARTMENT_ID FROM (SELECT ROWNUM AS RNUM, E.* FROM EMPLOYEES E WHERE ROWNUM <= 110)
WHERE RNUM >= 100;