CREATE OR REPLACE PROCEDURE STUDENT_PROCEDURE(VNO IN STUDENT.NO%TYPE, VPRICE IN STUDENT.PRICE%TYPE, VMESSAGE OUT VARCHAR2)
IS
    VSTUDENT_RT STUDENT%ROWTYPE;
BEGIN
     UPDATE STUDENT 
     SET PRICE = PRICE + VPRICE WHERE NO = VNO;
     COMMIT;
     SELECT * INTO VSTUDENT_RT FROM STUDENT WHERE NO = VNO;
     VMESSAGE := VSTUDENT_RT.NO||' 번호의 인상금액은 ' || VPRICE ||'이고 총 금액은'||VSTUDENT_RT.PRICE||'입니다.'; 
     DBMS_OUTPUT.PUT_LINE(VMESSAGE);
END;
/
VARIABLE VMESSAGE VARCHAR2(200);
EXECUTE STUDENT_PROCEDURE(1,10000,VMESSAGE);

SELECT * FROM STUDENT;
