-- PL/SQL
-- 내용을 EMPLOYEES 최고 경영자 사원번호, 이름, 담당업무, 부서번호를 출력하시오. 로우타입을 활용하시오.

DECLARE
    -- 로우 타입 변수 선언
    EMP_RECORD EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO EMP_RECORD
    FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
    DBMS_OUTPUT.PUT_LINE('사원번호: ' || EMP_RECORD.EMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE('이름: ' || EMP_RECORD.FIRST_NAME || ' ' || EMP_RECORD.LAST_NAME);
    DBMS_OUTPUT.PUT_LINE('부서번호: ' || EMP_RECORD.DEPARTMENT_ID);
END;
/

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL;