-- STORED PROCEDURE
-- EMPLOYEES에서 사용자 이름을 패턴으로 검색한 뒤 해당하는 사용자정보(사원번호,이름,급여)를 보여주시오.
SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE '%P%';


CREATE OR REPLACE NONEDITIONABLE PROCEDURE EMP_PROC2 (VWORD IN VARCHAR2)
IS 
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    CURSOR CURSOR_NAME(VWORD VARCHAR2)
    IS
    SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%'||VWORD||'%');

BEGIN
    FOR VEMP_ROWTYPE IN CURSOR_NAME(VWORD) LOOP
        DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME || ' / ' || VEMP_ROWTYPE.SALARY); 
        END LOOP;

END;
/
SHOW ERROR;
EXECUTE EMP_PROC2 ('K');
//
SELECT * FROM USER_TABLES;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONS_COlUMNS;
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;
SELECT * FROM USER_VIEWS;
SELECT * FROM USER_SOURCE;
SELECT * FROM USER_SEQUENCES;