-- PL/SQL
-- 내용을 EMPLOYEES 최고 경영자 사원번호, 이름, 담당업무, 부서번호를 출력하시오. 레코드변수를 활용하시오.

DECLARE
    -- 레코드 타입 (사원번호, 이름, 담당업무, 부서번호)
    TYPE EMP_RECORD_TYPE IS RECORD(
        VEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
        VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
        VLAST_NAME EMPLOYEES.LAST_NAME%TYPE,
        VDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE
    );
    -- 레코드 타입 변수 선언
    EMP_RECORD EMP_RECORD_TYPE;
BEGIN
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID INTO EMP_RECORD
    FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
    DBMS_OUTPUT.PUT_LINE('사원번호: ' || EMP_RECORD.VEMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE('이름: ' || EMP_RECORD.VFIRST_NAME || ' ' || EMP_RECORD.VLAST_NAME);
    DBMS_OUTPUT.PUT_LINE('부서번호: ' || EMP_RECORD.VDEPARTMENT_ID);
END;
/

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL;