-- PL/SQL
-- 내용을 EMPLOYEE 이름, 사원번호를 가져와서 출력하기

DECLARE
    VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    VEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN
    SELECT FIRST_NAME, EMPLOYEE_ID INTO VFIRST_NAME, VEMPLOYEE_ID
    FROM EMPLOYEES WHERE FIRST_NAME = 'Ellen';
    
    DBMS_OUTPUT.PUT_LINE('FIRST_NAME='||VFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE_ID='||VEMPLOYEE_ID);
END;
/
    SELECT FIRST_NAME, EMPLOYEE_ID FROM EMPLOYEES WHERE FIRST_NAME = 'Ellen';
    
    
-- 내용을 EMPLOYEES에 해당된 모든 직원 이름, 직업, 사원번호를 출력해주는 프로그램을 작성하시오. 

DECLARE
    -- 배열타입정의(테이블타입정의)
    TYPE FIRST_NAME_ARRAY_TYPE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY BINARY_INTEGER;
    TYPE JOB_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.JOB_ID%TYPE INDEX BY BINARY_INTEGER;
    TYPE EMPLOYEE_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.EMPLOYEE_ID%TYPE INDEX BY BINARY_INTEGER;
    -- 배열타입 변수 선언
    FIRST_NAME_ARRAY FIRST_NAME_ARRAY_TYPE;
    JOB_ID_ARRAY JOB_ID_ARRAY_TYPE;
    EMPLOYEE_ID_ARRAY EMPLOYEE_ID_ARRAY_TYPE;
    ROW_ARRAY EMPLOYEES%ROWTYPE;
    I BINARY_INTEGER := 0;
    J BINARY_INTEGER;
BEGIN
    -- 향상된 포문을 통해서 RESULT SET값을 한개씩 가져와서 각 컬럼배열에 저장한다.
    FOR ROW_ARRAY IN (SELECT * FROM EMPLOYEES) LOOP
        I := I + 1;
        FIRST_NAME_ARRAY(I) := ROW_ARRAY.FIRST_NAME;
        JOB_ID_ARRAY(I) := ROW_ARRAY.JOB_ID;
        EMPLOYEE_ID_ARRAY(I) := ROW_ARRAY.EMPLOYEE_ID;
    END LOOP;
    -- 향상된 포문을 이용해서 컬럼 배열값에 저장된 값을 가져와서 출력하시오.
    FOR J IN 1..I LOOP
        DBMS_OUTPUT.PUT_LINE(FIRST_NAME_ARRAY(J) || '  /  ' || JOB_ID_ARRAY(J) || '  /  ' || EMPLOYEE_ID_ARRAY(J));
        
    END LOOP;
END;
/

SELECT COUNT(*) FROM EMPLOYEES;