CREATE TABLE STUDENT (
    STU_NO NUMBER,                      -- 학번(PK)
    STU_NAME VARCHAR2(12) NOT NULL,     -- 이름
    EMAIL VARCHAR2(30) NOT NULL,        -- 이메일
    ADDRESS VARCHAR2(50) NOT NULL,      -- 주소
    PHONE VARCHAR2(20) NOT NULL,        -- 전화번호
    REG_DATE DATE NOT NULL              -- 등록일
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_STU_NO_PK PRIMARY KEY(STU_NO);

CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE SUBJECT (
    SUB_NO NUMBER,                      -- 과목코드(PK)
    SUB_NAME VARCHAR (20) NOT NULL,     -- 과목이름
    SCORE NUMBER NOT NULL,              -- 학점
    TOT NUMBER NOT NULL,                -- 총점
    AVR NUMBER NOT NULL,                -- 평점
    RNK NUMBER                          -- 랭크
);

ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_SUB_NO_PK PRIMARY KEY(SUB_NO);

CREATE SEQUENCE SUBJECT_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE TRAINEE (
    TRA_NO NUMBER,                      -- 수강번호(PK)
    STU_NO NUMBER,                      -- 학번(FK)
    SUB_NO NUMBER                       -- 과목코드(FK)
);

ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_TRA_NO_PK PRIMARY KEY(TRA_NO);
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_STUDENT_STU_NO_FK FOREIGN KEY(STU_NO) REFERENCES STUDENT(STU_NO) ON DELETE SET NULL;
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_SUBJECT_SUB_NO_FK FOREIGN KEY(SUB_NO) REFERENCES SUBJECT(SUB_NO) ON DELETE SET NULL;

CREATE SEQUENCE TRAINEE_SEQ
START WITH 1
INCREMENT BY 1;